version: '3'
services:
  flightreservation:
    image: flightreservation
    build:
      context: ./
      dockerfile: flightreservation.dockerfile
    ports:
    - 8087:8080
    volumes:
    - /data/flightreservation
    depends_on:
    - mysql-docker-container
    environment:
      WAIT_HOSTS: mysql-docker-container:3306
      WAIT_HOSTS_TIMEOUT: 3000
  mysql-docker-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    build:
      context: ./
      dockerfile: mysql.dockerfile
    environment:
    - MYSQL_ROOT_PASSWORD=akshay
    - MYSQL_DATABASE=reservation
    - MYSQL_USER=akshay
    - MYSQL_PASSWORD=akshay
    volumes:
    - /data/mysql